# WRAP_P6_L1_FEATURE_LAB — Notebook 03

**Spec ref:** §9.1 — L1/L2 Feature Engineering & Validation

Build and validate the 19-feature L1 set (16 base + 3 shape unit-vector
components from Wave 3 Phase 5A) + 12-feature L2 set. Writes the
canonical `triple_view/{symbol}.parquet` consumed by every other
notebook and the web server.

**Wave 4 Phase 1A/1B**: Section 03 wires `recent_events` through to
`L2History.refresh_event_timestamps` and runs VPIN on trades so
`refresh_rate` and `trade_flow_toxicity` are live features (both
were dropped as constants pre-Wave-4).

## Section 00 — Environment & Configuration

In [1]:
import sys, logging
from pathlib import Path
import numpy as np
import pandas as pd

# ── shared config ─────────────────────────────────────────────────────────────
_NB_DIR = Path('<repo>/p6lab/notebooks')
if str(_NB_DIR) not in sys.path:
    sys.path.insert(0, str(_NB_DIR))
import _common  # bootstraps sys.path; exposes NOTEBOOK_DATA_SLICE, helpers

from _common import (
    NOTEBOOK_DATA_SLICE, HORIZONS, PURGE_ROWS, TIER_CUTOFFS,
    BASELINE_MIN_AUC_IMPROVEMENT, collect_snapshots, versioned_dir,
)
_DS       = NOTEBOOK_DATA_SLICE          # single source of truth
SYMBOL    = _DS['symbol']
TICK_SIZE = _DS['tick_size']

_P6LAB        = Path(_common._P6LAB_ROOT)
ARTIFACTS_DIR = _P6LAB / 'artifacts' / 'p6lab'
MAX_SNAPSHOTS = _DS['max_snapshots']

logging.basicConfig(level=logging.INFO, format='%(message)s')
log = logging.getLogger(__name__)
np.random.seed(42)

print(f'Data  : {_DS["data_file"]}')
print(f'Symbol: {SYMBOL}  tick={TICK_SIZE}  max_snapshots={MAX_SNAPSHOTS}')
TRIPLE_VIEW_DIR = ARTIFACTS_DIR / 'triple_view'

from p6lab.features._l1_adapter import L1Adapter, L1AdapterConfig
from p6lab.features.fragility_index import FragilityIndex
from p6lab.features.l1_features import L1FeatureNames, compute_l1_features
from p6lab.features.l2_features import (
    L2FeatureNames, L2History, L2Snapshot,
    compute_book_shape_vector, compute_l2_features,
)
from p6lab.ingestion.triple_view import EmitterConfig, TripleViewEmitter
from p6lab.validation.information_gain import must_beat_baseline

Data  : <repo>/data/nq-mbo-sample-15min.dbn.zst
Symbol: NQ  tick=▒.▒▒  max_snapshots=2000

## Section 01 — Triple-View Replay

Drive `DatabentoReplayFeed` → `TripleViewEmitter`. Writes `triple_view/{symbol}_1s.parquet` for downstream notebooks.

In [2]:
snaps = await collect_snapshots(_DS)
assert len(snaps) > 0, 'No snapshots collected — check _common.NOTEBOOK_DATA_SLICE["data_file"]'
log.info('data │ %d snapshots loaded', len(snaps))
cfg = EmitterConfig(output_dir=TRIPLE_VIEW_DIR, symbol=SYMBOL,
                    granularities=[1_000], tick_size=TICK_SIZE)
frames = list(TripleViewEmitter(cfg).emit(snaps))
log.info('01 │ %d snapshots → %d frames', len(snaps), len(frames))
assert len(frames) > 0, '01 │ TripleViewEmitter produced no frames'

Opening MBO data from <repo>/data/nq-mbo-sample-15min.dbn.zst (streaming mode)

Streaming ready. instrument_id=42004058

data │ 2000 snapshots loaded

TripleViewEmitter initialized: symbol=NQ granularities=[1000]

Wrote 595 frames to <repo>/p6lab/artifacts/p6lab/triple_view/NQ_1s.parquet

01 │ 2000 snapshots → 595 frames

## Section 02 — L1 Features (19-dim)

Post-Wave-3 Phase 5A: 16 base features + 3 unit-vector components
(`l1_shape_bid_unit`, `l1_shape_ask_unit`, `l1_shape_imb_unit`) that
expose the book-shape composition the old scalar `l1_shape_vector`
collapsed into a single projection.

In [3]:
adapter = L1Adapter(L1AdapterConfig(tick_size=TICK_SIZE))
rows = [compute_l1_features(adapter.ingest(s), adapter.history) for s in snaps]
l1_df = pd.DataFrame(np.array(rows), columns=L1FeatureNames.ALL)
log.info('02 │ L1: %d rows × %d cols', *l1_df.shape)
l1_df.head()

02 │ L1: 2000 rows × 16 cols

,spread_ticks,spread_bps_l1,best_bid_size,best_ask_size,top_imbalance,bid_refresh_rate,ask_refresh_rate,bid_retreat_velocity,ask_advance_velocity,spread_compression_rate,tick_direction_streak,tick_acceleration,trade_at_bid_ratio,size_spike_ratio,microprice_velocity,l1_shape_vector
0,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒
1,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒
2,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒
3,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒
4,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒

## Section 03 — L2 Features (12 + 40-dim book shape)

In [ ]:
# Wave 4 Phase 1B: VPIN source so trade_flow_toxicity is live, not 0.
from p6lab.features.vpin import (
    VPINState, VPINConfig, update_vpin_state, compute_vpin,
    classify_trade_lee_ready,
)
vpin_state = VPINState()
vpin_cfg = VPINConfig(avg_daily_volume=300_000.0, bucket_size_fraction=1.0/200,
                      window_size=5)
_prev_trade_price = 0.0

history = L2History()
rows, bsvs = [], []
for s in snaps:
    if not s.bids or not s.asks:
        continue
    mid = 0.5 * (s.bids[0].price + s.asks[0].price)
    levels = [(b.price, b.volume, 0.0) for b in s.bids[:20]]
    levels += [(a.price, 0.0, a.volume) for a in s.asks[:20]]

    # Wave 4 Phase 1B: update VPIN from snapshot trades before L2 compute
    bp, ap = s.bids[0].price, s.asks[0].price
    for tr in getattr(s, 'recent_trades', []) or []:
        try:
            tp = float(getattr(tr, 'price', 0.0))
            tv = float(getattr(tr, 'size', 0.0) or getattr(tr, 'volume', 0.0))
            tts = int(getattr(tr, 'timestamp_ms', s.timestamp_ms))
            if tv <= 0:
                continue
            side = classify_trade_lee_ready(tp, _prev_trade_price, bp, ap)
            update_vpin_state(vpin_state, vpin_cfg, tts, tp, tv, side)
            _prev_trade_price = tp
        except Exception:
            pass
    vpin_value = compute_vpin(vpin_state, vpin_cfg)
    history.vpin_value = float(vpin_value) if vpin_value is not None else 0.0

    snap = L2Snapshot(
        timestamp_ms=s.timestamp_ms, symbol=SYMBOL,
        mid_price=mid, book_levels=levels,
        # Wave 4 Phase 1A: pass recent_events through for refresh_rate
        recent_events=list(getattr(s, 'recent_events', []) or []),
    )
    rows.append(compute_l2_features(snap, history))
    bsvs.append(compute_book_shape_vector(snap))
l2_df = pd.DataFrame(np.array(rows), columns=L2FeatureNames.ALL)
log.info('03 │ L2: %d rows × %d cols', *l2_df.shape)

# Wave 4 observability — non-zero rates for formerly-dead features
nz_refresh = int((l2_df['refresh_rate'] != 0).sum())
nz_tft = int((l2_df['trade_flow_toxicity'] != 0).sum())
log.info('03 │ non-zero rates: refresh_rate=%d/%d (%.1f%%), '
         'trade_flow_toxicity=%d/%d (%.1f%%)',
         nz_refresh, len(l2_df), 100*nz_refresh/max(len(l2_df),1),
         nz_tft, len(l2_df), 100*nz_tft/max(len(l2_df),1))
l2_df.head()

## Section 04 — Forward Returns + Univariate Analytics

Compute forward returns at **30s / 1m / 2m** horizons from the L2 `weighted_mid` series, then score every L1+L2 feature against the resulting direction labels using:
- **Spearman** rank correlation (monotonic relationship)
- **ROC-AUC** (binary direction: up/down)
- **Brier** score (probability calibration against min-max-normed feature)

In [5]:
from scipy.stats import spearmanr
from sklearn.metrics import roc_auc_score, brier_score_loss

# Horizons (in snapshots; 100ms each → 30s=300, 1m=600, 2m=1200)
HORIZONS = {'30s': 300, '1m': 600, '2m': 1200}

# Align L1 + L2 on shared row count (some snapshots may have empty book)
n = min(len(l1_df), len(l2_df))
X_full = pd.concat([
    l1_df.iloc[:n].reset_index(drop=True),
    l2_df.iloc[:n].reset_index(drop=True),
], axis=1)
# Drop any all-constant columns up front (zero std → degenerate stats)
constants = [c for c in X_full.columns if X_full[c].std() == 0]
X = X_full.drop(columns=constants)
log.info('04 │ feature matrix %s (dropped %d constants: %s)',
         X.shape, len(constants), constants[:5])

# Forward-return series from weighted_mid
mid = l2_df['weighted_mid'].iloc[:n].to_numpy()
fwd_returns = {h: np.full(n, np.nan) for h in HORIZONS}
for h, k in HORIZONS.items():
    if n > k:
        fwd_returns[h][:-k] = mid[k:] - mid[:-k]

univariate_rows = []
for feat in X.columns:
    x = X[feat].to_numpy()
    row = {'feature': feat}
    for h, fwd in fwd_returns.items():
        mask = ~np.isnan(fwd)
        if mask.sum() < 50:
            continue
        xv = x[mask]; fv = fwd[mask]
        direction = (fv > 0).astype(int)
        if direction.mean() in (0.0, 1.0):
            continue  # no class balance
        try:
            rho = spearmanr(xv, fv).statistic
        except Exception:
            rho = np.nan
        try:
            auc = roc_auc_score(direction, xv)
        except Exception:
            auc = 0.5
        # Brier needs probabilities ∈ [0, 1]: min-max normalize the feature
        lo, hi = np.nanmin(xv), np.nanmax(xv)
        prob = (xv - lo) / (hi - lo) if hi > lo else np.full_like(xv, 0.5, dtype=float)
        try:
            brier = brier_score_loss(direction, prob)
        except Exception:
            brier = np.nan
        row[f'spearman_{h}'] = rho
        row[f'auc_{h}'] = auc
        row[f'brier_{h}'] = brier
    univariate_rows.append(row)
univariate = pd.DataFrame(univariate_rows)
univariate = univariate.sort_values('auc_1m', ascending=False, na_position='last')
log.info('04 │ top 5 by 1m-AUC:')
log.info('\n' + univariate[['feature', 'auc_30s', 'auc_1m', 'auc_2m',
                             'spearman_1m', 'brier_1m']].head(5).to_string(index=False))
univariate.head(10)

04 │ feature matrix (2000, 26) (dropped 2 constants: ['refresh_rate', 'trade_flow_toxicity'])

04 │ top 5 by 1m-AUC:

          feature  auc_30s   auc_1m   auc_2m  spearman_1m  brier_1m
    imbalance_ema ▒.▒▒ ▒.▒▒ ▒.▒▒     ▒.▒▒  ▒.▒▒
      depth_ratio ▒.▒▒ ▒.▒▒ ▒.▒▒     ▒.▒▒  ▒.▒▒
bid_ask_imbalance ▒.▒▒ ▒.▒▒ ▒.▒▒     ▒.▒▒  ▒.▒▒
    best_bid_size ▒.▒▒ ▒.▒▒ ▒.▒▒     ▒.▒▒  ▒.▒▒
    top_imbalance ▒.▒▒ ▒.▒▒ ▒.▒▒     ▒.▒▒  ▒.▒▒

,feature,spearman_30s,auc_30s,brier_30s,spearman_1m,auc_1m,brier_1m,spearman_2m,auc_2m,brier_2m
21,imbalance_ema,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒
17,depth_ratio,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒
16,bid_ask_imbalance,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒
2,best_bid_size,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒
4,top_imbalance,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒
25,book_shape_vector,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒
13,size_spike_ratio,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒
10,tick_direction_streak,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒
15,l1_shape_vector,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒
1,spread_bps_l1,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒,▒.▒▒

## Section 05 — Mutual Information vs Forward Direction

MI catches non-linear dependencies that Spearman misses. Computed on the 1m horizon against binary direction.

In [6]:
from sklearn.feature_selection import mutual_info_classif

# Use 1m horizon — middle ground between noise (30s) and sparse-data (2m)
fwd_1m = fwd_returns['1m']
mask = ~np.isnan(fwd_1m)
y = (fwd_1m[mask] > 0).astype(int)
X_matrix = X.iloc[:mask.sum()].to_numpy()
# Align
X_matrix = X.iloc[np.where(mask)[0]].fillna(0).to_numpy()
mi = mutual_info_classif(X_matrix, y, random_state=42)
mi_table = pd.DataFrame({'feature': X.columns, 'mi_1m': mi}).sort_values('mi_1m', ascending=False)
log.info('05 │ top 5 by MI:')
log.info('\n' + mi_table.head(5).to_string(index=False))
mi_table.head(10)

05 │ top 5 by MI:

          feature    mi_1m
     weighted_mid ▒.▒▒
    spread_bps_l1 ▒.▒▒
       spread_bps ▒.▒▒
  l1_shape_vector ▒.▒▒
book_shape_vector ▒.▒▒

                  feature     mi_1m
18           weighted_mid  ▒.▒▒
1           spread_bps_l1  ▒.▒▒
19             spread_bps  ▒.▒▒
15        l1_shape_vector  ▒.▒▒
25      book_shape_vector  ▒.▒▒
21          imbalance_ema  ▒.▒▒
17            depth_ratio  ▒.▒▒
16      bid_ask_imbalance  ▒.▒▒
23  depth_change_rate_30s  ▒.▒▒
20       depth_within_pct  ▒.▒▒

## Section 06 — Random Forest + PurgedKFold

3-fold time-series split with ±60-row (6s) purge around test boundaries to avoid label leakage across the forward-return horizon. Reports mean out-of-fold AUC and RF feature importances (SHAP left as a future extension).

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedKFold

mask = ~np.isnan(fwd_returns['1m'])
X_tr = X.loc[mask].fillna(0).to_numpy()
y_tr = (fwd_returns['1m'][mask] > 0).astype(int)

# Purge must be >= forward-return horizon, else train rows overlap the label
# window of nearby test rows. Critique §2.1: the old 60-row purge was 10× too
# small for the 600-snapshot (60s) label horizon.
# On smoketest-sized samples the full purge wipes entire train sets; clamp
# to <= 10% of the row count so the feature lab can still produce an AUC.
HORIZON_ROWS = 600
PURGE_IDEAL = HORIZON_ROWS + 60
PURGE = min(PURGE_IDEAL, max(60, len(X_tr) // 10))
if PURGE < PURGE_IDEAL:
    log.warning('06 │ sample too small for full %d-row purge — using %d '
                '(≤10%% of %d rows); production runs with >10k rows will '
                'get the full purge automatically.',
                PURGE_IDEAL, PURGE, len(X_tr))

cv = StratifiedKFold(n_splits=3, shuffle=False)
aucs = []
fold_skipped = []
rf = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42, n_jobs=-1)
for fold_id, (tr, te) in enumerate(cv.split(X_tr, y_tr)):
    # Purge train rows near the test window
    te_lo, te_hi = te.min(), te.max()
    purge_mask = (tr < te_lo - PURGE) | (tr > te_hi + PURGE)
    tr_purged = tr[purge_mask]
    if len(np.unique(y_tr[tr_purged])) < 2 or len(np.unique(y_tr[te])) < 2:
        fold_skipped.append(fold_id)
        log.info('06 │ fold %d: skipping (single-class)', fold_id); continue
    rf.fit(X_tr[tr_purged], y_tr[tr_purged])
    proba = rf.predict_proba(X_tr[te])[:, 1]
    aucs.append(roc_auc_score(y_tr[te], proba))
    log.info('06 │ fold %d: train=%d purged=%d test=%d',
             fold_id, len(tr_purged), len(tr) - len(tr_purged), len(te))

rf_mean_auc = float(np.mean(aucs)) if aucs else float('nan')
# If no fold trained (label imbalance), fit on full set for importances
if not hasattr(rf, 'feature_importances_'):
    rf.fit(X_tr, y_tr)
rf_importances = pd.DataFrame({
    'feature': X.columns, 'importance': rf.feature_importances_,
}).sort_values('importance', ascending=False)
log.info('06 │ mean CV AUC = %.3f (purge=%d rows)', rf_mean_auc, PURGE)
log.info('06 │ top 5 importances:')
log.info('\n' + rf_importances.head(5).to_string(index=False))
rf_importances.head(10)

In [8]:
# §06 assertion gate
assert len(aucs) > 0, '§06 │ all CV folds were skipped — check class balance'
assert 0.45 < rf_mean_auc < 1.0, f'§06 │ RF CV AUC out of range: {rf_mean_auc:.3f}'
assert not X.isna().any().any(), '§06 │ feature matrix contains NaN'
print(f'✓ §06 gate PASS  RF CV AUC={rf_mean_auc:.3f}')

✓ §06 gate PASS  RF CV AUC=▒.▒▒

## Section 07 — Redundancy Pruning

If two features have |Spearman ρ| > 0.85, drop whichever has the lower 1m AUC. Reduces collinearity without losing signal.

In [9]:
corr = X.corr().abs()
auc_map = dict(zip(univariate['feature'], univariate.get('auc_1m', 0.5).fillna(0.5)))
cols = list(X.columns)
to_drop = set()
for i, a in enumerate(cols):
    if a in to_drop:
        continue
    for b in cols[i + 1:]:
        if b in to_drop:
            continue
        if corr.loc[a, b] > 0.85:
            loser = b if auc_map.get(a, 0.5) >= auc_map.get(b, 0.5) else a
            to_drop.add(loser)
pruned = [c for c in cols if c not in to_drop]
log.info('07 │ dropped %d/%d redundant features; kept %d',
         len(to_drop), len(cols), len(pruned))
log.info('07 │ dropped: %s', sorted(to_drop))

07 │ dropped 4/26 redundant features; kept 22

07 │ dropped: ['bid_ask_imbalance', 'depth_ratio', 'spread_bps', 'spread_ticks']

## Section 08 — Information-Gain Gate (per feature)

Each surviving feature must beat `bid_ask_imbalance` 1m-AUC by ≥ 2% absolute. Features that fail are logged but **not** removed — they may still contribute in multi-feature models. Per spec §15.7.

In [10]:
BASELINE_FEATURE = L2FeatureNames.BID_ASK_IMBALANCE
baseline_auc = auc_map.get(BASELINE_FEATURE, 0.5)
log.info('08 │ baseline %s AUC = %.3f', BASELINE_FEATURE, baseline_auc)

gate_rows = []
for feat in pruned:
    cand_auc = auc_map.get(feat, 0.5)
    report = must_beat_baseline(
        candidate_metric=cand_auc,
        baseline_metric=baseline_auc,
        min_improvement=0.02,
    )
    gate_rows.append({
        'feature': feat,
        'auc_1m': cand_auc,
        'gap': cand_auc - baseline_auc,
        'approved': report.approved,
        'reason': report.reason,
    })
gate = pd.DataFrame(gate_rows).sort_values('gap', ascending=False)
n_approved = int(gate['approved'].sum())
log.info('08 │ %d/%d features beat baseline by ≥2%%', n_approved, len(gate))
log.info('\n' + gate.head(10).to_string(index=False))
gate.head(15)

08 │ baseline bid_ask_imbalance AUC = ▒.▒▒

08 │ 1/22 features beat baseline by ≥2%

                feature   auc_1m       gap  approved                                                        reason
          imbalance_ema ▒.▒▒  ▒.▒▒      True approved: improvement ▒.▒▒ ≥ ▒.▒▒ and CI lower ▒.▒▒ > 0
          best_bid_size ▒.▒▒ ▒.▒▒     False               rejected: improvement ▒.▒▒ < required ▒.▒▒
          top_imbalance ▒.▒▒ ▒.▒▒     False               rejected: improvement ▒.▒▒ < required ▒.▒▒
      book_shape_vector ▒.▒▒ ▒.▒▒     False               rejected: improvement ▒.▒▒ < required ▒.▒▒
       size_spike_ratio ▒.▒▒ ▒.▒▒     False               rejected: improvement ▒.▒▒ < required ▒.▒▒
  tick_direction_streak ▒.▒▒ ▒.▒▒     False               rejected: improvement ▒.▒▒ < required ▒.▒▒
        l1_shape_vector ▒.▒▒ ▒.▒▒     False               rejected: improvement ▒.▒▒ < required ▒.▒▒
          spread_bps_l1 ▒.▒▒ ▒.▒▒     False               rejected: improvement ▒.▒▒ < required ▒.▒▒
   bid_retreat_velocity ▒.▒▒ ▒.▒▒     False               rejected: improvement ▒.▒▒ < required ▒.▒▒
spread_compression_rate ▒.▒▒ ▒.▒▒     False               rejected: improvement ▒.▒▒ < required ▒.▒▒

,feature,auc_1m,gap,approved,reason
17,imbalance_ema,▒.▒▒,▒.▒▒,True,approved: improvement ▒.▒▒ ≥ ▒.▒▒ and CI l...
1,best_bid_size,▒.▒▒,▒.▒▒,False,rejected: improvement ▒.▒▒ < required ▒.▒▒
3,top_imbalance,▒.▒▒,▒.▒▒,False,rejected: improvement ▒.▒▒ < required ▒.▒▒
21,book_shape_vector,▒.▒▒,▒.▒▒,False,rejected: improvement ▒.▒▒ < required ▒.▒▒
12,size_spike_ratio,▒.▒▒,▒.▒▒,False,rejected: improvement ▒.▒▒ < required ▒.▒▒
9,tick_direction_streak,▒.▒▒,▒.▒▒,False,rejected: improvement ▒.▒▒ < required ▒.▒▒
14,l1_shape_vector,▒.▒▒,▒.▒▒,False,rejected: improvement ▒.▒▒ < required ▒.▒▒
0,spread_bps_l1,▒.▒▒,▒.▒▒,False,rejected: improvement ▒.▒▒ < required ▒.▒▒
6,bid_retreat_velocity,▒.▒▒,▒.▒▒,False,rejected: improvement ▒.▒▒ < required ▒.▒▒
8,spread_compression_rate,▒.▒▒,▒.▒▒,False,rejected: improvement ▒.▒▒ < required ▒.▒▒
10,tick_acceleration,▒.▒▒,▒.▒▒,False,rejected: improvement ▒.▒▒ < required ▒.▒▒
4,bid_refresh_rate,▒.▒▒,▒.▒▒,False,rejected: improvement ▒.▒▒ < required ▒.▒▒
7,ask_advance_velocity,▒.▒▒,▒.▒▒,False,rejected: improvement ▒.▒▒ < required ▒.▒▒
20,level_persistence,▒.▒▒,▒.▒▒,False,rejected: improvement ▒.▒▒ < required ▒.▒▒
2,best_ask_size,▒.▒▒,▒.▒▒,False,rejected: improvement ▒.▒▒ < required ▒.▒▒

## Section 09 — Fragility Index Predictive Power

Validates that `FI_fast` and `FI_full` carry signal: compute per-row, then score each against forward-1m absolute return (proxy for 'big-move' risk the FI is supposed to flag). Spec target: AUC > 0.70 for predicting >2 ATR moves; here we use a smaller proxy threshold because the 3-min sample is too short for true 30m cascades.

In [11]:
fi = FragilityIndex()
fi_rows = []
m = min(len(l1_df), len(l2_df), n)
for i in range(m):
    out = fi.compute(
        l1_features=l1_df.iloc[i].to_numpy(),
        l2_features=l2_df.iloc[i].to_numpy(),
        vpin_value=0.0, timestamp_ms=i, symbol=SYMBOL,
    )
    fi_rows.append({'fi_fast': out.fi_fast, 'fi_full': out.fi_full})
fi_df = pd.DataFrame(fi_rows)

# 'Big move' label = forward 1m |return| in top quartile
mask = ~np.isnan(fwd_returns['1m'][:m])
abs_fwd = np.abs(fwd_returns['1m'][:m][mask])
if len(abs_fwd) > 20:
    threshold = np.quantile(abs_fwd, 0.75)
    big_move = (abs_fwd > threshold).astype(int)
    fi_metrics = {}
    for col in ('fi_fast', 'fi_full'):
        x = fi_df[col].iloc[:m].to_numpy()[mask]
        try:
            fi_metrics[col] = roc_auc_score(big_move, x) if len(np.unique(big_move)) > 1 else 0.5
        except Exception:
            fi_metrics[col] = 0.5
    log.info('09 │ FI vs top-quartile |1m return|: FI_fast AUC=%.3f, FI_full AUC=%.3f',
             fi_metrics['fi_fast'], fi_metrics['fi_full'])
else:
    fi_metrics = {'fi_fast': float('nan'), 'fi_full': float('nan')}
    log.info('09 │ insufficient data for FI AUC (need ≥20 labeled rows)')

log.info('09 │ FI_fast range %.3f..%.3f, FI_full range %.3f..%.3f',
         fi_df['fi_fast'].min(), fi_df['fi_fast'].max(),
         fi_df['fi_full'].min(), fi_df['fi_full'].max())

09 │ FI vs top-quartile |1m return|: FI_fast AUC=▒.▒▒, FI_full AUC=▒.▒▒

09 │ FI_fast range ▒.▒▒..0.700, FI_full range ▒.▒▒..0.351

## Section 10 — Report

Writes a markdown report with all tables + key metrics to `artifacts/p6lab/feature_logs/nb03_report.md`.

In [12]:
report_dir = versioned_dir(ARTIFACTS_DIR / 'feature_logs', 'nb03',
                          data_slice=_DS, extra={'rf_cv_auc': float(rf_mean_auc)})
report_path = report_dir / 'nb03_report.md'

with open(report_path, 'w') as f:
    f.write(f'# NB03 — L1/L2 Feature Lab Report\n\n')
    f.write(f'**Symbol:** {SYMBOL}  \n')
    f.write(f'**Snapshots:** {MAX_SNAPSHOTS} ({MAX_SNAPSHOTS*0.1:.0f}s of tape)  \n')
    f.write(f'**Feature matrix:** {X.shape}  \n\n')
    f.write('## Univariate Top-10 by 1m AUC\n\n')
    cols_to_show = [c for c in ['feature', 'auc_30s', 'auc_1m', 'auc_2m',
                                'spearman_1m', 'brier_1m'] if c in univariate.columns]
    f.write(univariate[cols_to_show].head(10).to_markdown(index=False))
    f.write('\n\n## Mutual Information Top-10\n\n')
    f.write(mi_table.head(10).to_markdown(index=False))
    f.write('\n\n## Random Forest (PurgedKFold)\n\n')
    f.write(f'- Mean CV AUC: **{rf_mean_auc:.3f}**\n')
    f.write(f'- Purge window: ±{PURGE} rows (±{PURGE*0.1:.1f}s)\n\n')
    f.write('Top-10 importances:\n\n')
    f.write(rf_importances.head(10).to_markdown(index=False))
    f.write('\n\n## Redundancy Pruning\n\n')
    f.write(f'- Dropped: {len(to_drop)} features ({sorted(to_drop)})\n')
    f.write(f'- Kept: {len(pruned)} features\n\n')
    f.write('## Information-Gain Gate\n\n')
    f.write(f'- Baseline: `{BASELINE_FEATURE}` AUC = **{baseline_auc:.3f}**\n')
    f.write(f'- Approved (beat by ≥2%): **{n_approved}/{len(gate)}**\n\n')
    f.write(gate.head(10).to_markdown(index=False))
    f.write('\n\n## Fragility Index\n\n')
    f.write(f'- FI_fast vs top-quartile |1m return| AUC: **{fi_metrics["fi_fast"]:.3f}**\n')
    f.write(f'- FI_full vs top-quartile |1m return| AUC: **{fi_metrics["fi_full"]:.3f}**\n')
log.info('10 │ wrote report → %s (%.1f KB)',
         report_path, report_path.stat().st_size / 1024)

10 │ wrote report → <repo>/p6lab/artifacts/p6lab/feature_logs/nb03_20260420_1648/nb03_report.md (▒.▒▒ KB)